services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  react-service:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.frontend
    depends_on:
      - backend
    expose:
      - "8080"
    volumes:
      - static_volume:/static

  tls:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.tls
    depends_on:
      - react-service
    ports:
      - "443:443"
    volumes:
      - /home/jpdevops/code/python/django/ecs_fs_sample_app/nginx/selfsigned.crt:/etc/ssl/certs/selfsigned.crt:ro
      - /home/jpdevops/code/python/django/ecs_fs_sample_app/nginx/selfsigned-rsa.key:/etc/ssl/private/selfsigned-rsa.key:ro

volumes:
  static_volume:
