services:
  backend:
    build: ./backend
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  react-service:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.frontend
    depends_on:
      - backend
    expose:
      - "8080"
    volumes:
      - static_volume:/static

  tls:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.tls
    depends_on:
      - react-service
    ports:
      - "443:443"
    environment:
      - TLS_CERT
      - TLS_KEY

volumes:
  static_volume: